"""Add group core model

Revision ID: 01826fb4b01b
Revises: 916f695d8fa9
Create Date: 2026-03-26 15:58:06.514871

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01826fb4b01b"
down_revision = "916f695d8fa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("shortname", sa.String(length=64), nullable=True),
        sa.Column("abbreviation", sa.String(length=64), nullable=True),
        sa.Column("contact", sa.String(length=120), nullable=True),
        sa.Column("contact_sec", sa.String(length=120), nullable=True),
        sa.Column("about_blurb", sa.String(length=2400), nullable=True),
        sa.Column("more_info_url", sa.String(length=2400), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("invite_only", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Integer(), nullable=True),
        sa.Column("init_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("membership_level", sa.Integer(), nullable=True),
        sa.Column("account_type", sa.String(length=64), nullable=True),
        sa.Column("group_type", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("primary_activity", sa.String(length=64), nullable=True),
        sa.Column("type", sa.String(length=128), nullable=True),
        sa.Column("subtype", sa.String(length=128), nullable=True),
        sa.Column("date_founded", sa.DateTime(), nullable=True),
        sa.Column("dues", sa.Float(), nullable=True),
        sa.Column("waiver_url", sa.String(length=2048), nullable=True),
        sa.Column("waiver_date", sa.DateTime(), nullable=True),
        sa.Column("logo", sa.String(length=2048), nullable=True),
        sa.Column("profile_photo", sa.String(length=2048), nullable=True),
        sa.Column("hero_video", sa.String(length=2048), nullable=True),
        sa.Column("home_town", sa.String(length=256), nullable=True),
        sa.Column("home_state", sa.String(length=256), nullable=True),
        sa.Column("home_country", sa.String(length=256), nullable=True),
        sa.Column("home_latlng", sa.String(length=256), nullable=True),
        sa.Column("home_add", sa.String(length=256), nullable=True),
        sa.Column("full_address", sa.String(length=2048), nullable=True),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_group_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_group_shortname"), ["shortname"], unique=True)

    op.create_table(
        "group_membership",
        sa.Column("groups", sa.Integer(), nullable=False),
        sa.Column("members", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["groups"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["members"],
            ["membership.id"],
        ),
        sa.PrimaryKeyConstraint("groups", "members"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_membership")
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_shortname"))
        batch_op.drop_index(batch_op.f("ix_group_name"))

    op.drop_table("group")
    # ### end Alembic commands ###
