"""Add group dues model

Revision ID: 22e254aae7bd
Revises: af2ba027dd33
Create Date: 2026-03-26 22:16:59.559297

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22e254aae7bd"
down_revision = "af2ba027dd33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_dues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("fee", sa.Float(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_dues")
    # ### end Alembic commands ###
