"""Add event core model

Revision ID: 3bc99d67c70b
Revises: 6f0342e2768f
Create Date: 2026-03-26 20:37:02.917454

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bc99d67c70b"
down_revision = "6f0342e2768f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("date_start", sa.DateTime(), nullable=False),
        sa.Column("date_end", sa.DateTime(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("primary_activity", sa.String(length=64), nullable=True),
        sa.Column("type", sa.String(length=256), nullable=True),
        sa.Column("subtype", sa.String(length=256), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("reg_url", sa.String(length=2048), nullable=True),
        sa.Column("photo_url", sa.String(length=2048), nullable=True),
        sa.Column("logo", sa.String(length=2048), nullable=True),
        sa.Column("profile_photo", sa.String(length=2048), nullable=True),
        sa.Column("notes", sa.String(length=2048), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("town", sa.String(length=256), nullable=True),
        sa.Column("state", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=256), nullable=True),
        sa.Column("latlng", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_events",
        sa.Column("calendars", sa.Integer(), nullable=False),
        sa.Column("events", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendars"],
            ["calendar.id"],
        ),
        sa.ForeignKeyConstraint(
            ["events"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("calendars", "events"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_events")
    op.drop_table("event")
    # ### end Alembic commands ###
