"""Add lookup tables

Revision ID: 64c523e57c65
Revises:
Create Date: 2026-03-26 15:04:32.355879

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64c523e57c65"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_invitation_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )
    op.create_table(
        "group_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_role")
    op.drop_table("event_invitation_status")
    # ### end Alembic commands ###
