"""Add calendar core model

Revision ID: 6f0342e2768f
Revises: 01826fb4b01b
Create Date: 2026-03-26 19:19:15.016629

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f0342e2768f"
down_revision = "01826fb4b01b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("primary_activity", sa.String(length=64), nullable=True),
        sa.Column("type", sa.String(length=256), nullable=True),
        sa.Column("subtype", sa.String(length=256), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("photo_url", sa.String(length=2048), nullable=True),
        sa.Column("logo", sa.String(length=2048), nullable=True),
        sa.Column("profile_photo", sa.String(length=2048), nullable=True),
        sa.Column("notes", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar")
    # ### end Alembic commands ###
