"""Add group external links

Revision ID: af2ba027dd33
Revises: 30a8db42e7d8
Create Date: 2026-03-26 22:11:17.841446

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af2ba027dd33"
down_revision = "30a8db42e7d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_external_url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=True),
        sa.Column("subtype", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("tags", sa.String(length=2048), nullable=True),
        sa.Column("icon", sa.String(length=256), nullable=True),
        sa.Column("img", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_external_url")
    # ### end Alembic commands ###
