"""Add event fee model

Revision ID: ba5657ad5048
Revises: 22e254aae7bd
Create Date: 2026-03-26 22:22:00.434563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba5657ad5048"
down_revision = "22e254aae7bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_fee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event", sa.Integer(), nullable=True),
        sa.Column("fee", sa.Float(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_fee")
    # ### end Alembic commands ###
