"""Add event participation bridge

Revision ID: bfa1b258d025
Revises: 3bc99d67c70b
Create Date: 2026-03-26 20:41:01.237493

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfa1b258d025"
down_revision = "3bc99d67c70b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_attendance",
        sa.Column("events", sa.Integer(), nullable=False),
        sa.Column("attendance", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendance"],
            ["event_invitation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["events"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("events", "attendance"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_attendance")
    # ### end Alembic commands ###
